server:
  port: 9090
spring:
  application:
    name: ms-consumer-order
  zipkin:
    base-url: http://localhost:9411/
  sleuth:
    sampler:
      percentage: 1.0
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

#Configure Ribbon load balancer strategy. Default RoundRobinRule
ms-provider-user:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

hystrix:
  command:
    default:
      circuitBreaker:
        requestVolumeThreshold: 5
    execution:
      isolation:
        thread:
          timeoutInMilliseconds: 4000

feign:
  hystrix:
    enabled: true

#For Hystrix stream
management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    org.springframework.cloud.sleuth: DEBUG