server:
  port: 8001
spring:
  application:
    name: ms-provider-user
  boot:
    admin:
      client:
        url: http://localhost:9999        # spring boot admin服务端地址，搜集客户端监控数据
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:                           # 指定数据源
    platform: h2                        # 指定数据源类型
    schema: classpath:schema.sql        # 指定h2数据库的建表脚本
    data: classpath:data.sql            # 指定h2数据库的数据脚本
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
  h2:
    console:
      enabled: true
      path: /h2
  zipkin:
    base-url: http://localhost:9411/
  sleuth:
    sampler:
      percentage: 1.0
logging:                                # 配置日志级别，让hibernate打印出执行的SQL
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      #defaultZone: http://peer1:8761/eureka/,http://peer2:8762/eureka/     #HA
      #defaultZone: http://user:password123@localhost:8761/eureka/        #Security
  instance:
    prefer-ip-address: true


management:
  server:
    port: 8899  #Actuator管理端口调整成8899,独立的端口可以做安全控制
  health:
    mail:
      enabled: false
  endpoints:
    web:
      exposure:
        include: "*"